thread = 2
duration = 1

[mongo]
connection_string = "mongodb://xavient:1%4034567b@127.0.0.1:27017"
database = "killer"
collection = "test"

[influxdb]
connection_string = "127.0.0.1:8089"
database = "mgobench"

[testcases]

  # test cases for mongo bench
  
  [testcases.flatT1InsertTaskTest]
  duration = "5s"
  name = "flatT1InsertTaskTest"

  [testcases.emptyTest]
  duration = "5s"
  name = "emptyTest"

  [testcases.flatT1DocTest]
  duration = "5s"
  name = "flatt1docTest"
