thread = 2
duration = 10
#logfile = "/var/log/test.log"
#mongos = [ "localhost:7564", "localhost:7564", "localhost:7564" ]
#database = "test"
#collection = "test"

[mongo]
connection_string = "mongodb://localhost:27017/"
database = "mgobench"
collection = "test"

[influxdb]
connection_string = "mongodb://localhost:27017/"
database = "mgobench"

[testcases]
  # test cases for mongo bench
  [testcases.a]
  duration = "1hr"
  name = "twotest"

  [testcases.b]
  duration = "1hr"
  name = "onetest"
